## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

In [ ]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
print(unique_counts)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
cutoff = 100
application_types_to_replace = application_type_counts[application_type_counts < cutoff].index

# use the variable name `application_types_to_replace`

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

# Choose a cutoff value and create a list of classifications to be replaced
cutoff = 100
classifications_to_replace = classification_counts[classification_counts < cutoff].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts[classification_counts > 1])

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff = 100
classifications_to_replace = classification_counts[classification_counts < cutoff].index


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_encoded = pd.get_dummies(application_df)
application_df_encoded.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
y = application_df_encoded["IS_SUCCESSFUL"].values
X = application_df_encoded.drop(["IS_SUCCESSFUL"], axis=1).values
print(X.shape, y.shape)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(34299, 50) (34299,)
(27439, 50) (6860, 50) (27439,) (6860,)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

**bold text**## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = X_train_scaled.shape[1]
hidden_nodes_layer1 = 80
hidden_nodes_layer2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, activation='relu', input_dim=number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                4080

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 6541 (25.55 KB)
Trainable params: 6541 (25.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
858/858 [==============================] - 4s 2ms/step - loss: 0.5694 - accuracy: 0.7210
Epoch 2/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7284
Epoch 3/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5497 - accuracy: 0.7309
Epoch 4/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5478 - accuracy: 0.7311
Epoch 5/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5475 - accuracy: 0.7339
Epoch 6/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7327
Epoch 7/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7334
Epoch 8/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7338
Epoch 9/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7341
Epoch 10/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5432 - accuracy: 0.7342
Epoch 11/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5424 - accuracy: 0.7341
Epoch 12/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7341
Epoch 13/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5414 - accuracy: 0.7350
Epoch 14/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 15/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7353
Epoch 16/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5412 - accuracy: 0.7347
Epoch 17/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5408 - accuracy: 0.7359
Epoch 18/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7360
Epoch 19/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 20/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7363
Epoch 21/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7372
Epoch 22/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7371
Epoch 23/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5390 - accuracy: 0.7370
Epoch 24/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7378
Epoch 25/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7384
Epoch 26/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7369
Epoch 27/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7372
Epoch 28/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5379 - accuracy: 0.7372
Epoch 29/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 30/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7375
Epoch 31/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7378
Epoch 32/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5370 - accuracy: 0.7384
Epoch 33/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7377
Epoch 34/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 35/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7379
Epoch 36/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7382
Epoch 37/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 38/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7383
Epoch 39/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7391
Epoch 40/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7386
Epoch 41/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5356 - accuracy: 0.7392
Epoch 42/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5350 - accuracy: 0.7395
Epoch 43/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7393
Epoch 44/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7394
Epoch 45/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5350 - accuracy: 0.7403
Epoch 46/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7392
Epoch 47/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5348 - accuracy: 0.7390
Epoch 48/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5344 - accuracy: 0.7392
Epoch 49/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7389
Epoch 50/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7393
Epoch 51/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7407
Epoch 52/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5345 - accuracy: 0.7403
Epoch 53/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5339 - accuracy: 0.7396
Epoch 54/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7401
Epoch 55/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7393
Epoch 56/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7408
Epoch 57/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7396
Epoch 58/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.7403
Epoch 59/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5334 - accuracy: 0.7407
Epoch 60/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5336 - accuracy: 0.7396
Epoch 61/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7403
Epoch 62/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7403
Epoch 63/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7403
Epoch 64/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5334 - accuracy: 0.7403
Epoch 65/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 66/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5332 - accuracy: 0.7405
Epoch 67/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7408
Epoch 68/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7402
Epoch 69/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7395
Epoch 70/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5324 - accuracy: 0.7401
Epoch 71/100
858/858 [==============================] - 4s 4ms/step - loss: 0.5325 - accuracy: 0.7411
Epoch 72/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5327 - accuracy: 0.7405
Epoch 73/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7401
Epoch 74/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7404
Epoch 75/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7409
Epoch 76/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7408
Epoch 77/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7409
Epoch 78/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5321 - accuracy: 0.7414
Epoch 79/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7397
Epoch 80/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7410
Epoch 81/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7409
Epoch 82/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7409
Epoch 83/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7411
Epoch 84/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5320 - accuracy: 0.7407
Epoch 85/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5315 - accuracy: 0.7414
Epoch 86/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7412
Epoch 87/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 88/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5316 - accuracy: 0.7411
Epoch 89/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7413
Epoch 90/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5310 - accuracy: 0.7411
Epoch 91/100
858/858 [==============================] - 3s 4ms/step - loss: 0.5313 - accuracy: 0.7409
Epoch 92/100
858/858 [==============================] - 2s 3ms/step - loss: 0.5311 - accuracy: 0.7407
Epoch 93/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7426
Epoch 94/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7406
Epoch 95/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5317 - accuracy: 0.7406
Epoch 96/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7419
Epoch 97/100
858/858 [==============================] - 3s 3ms/step - loss: 0.5313 - accuracy: 0.7414
Epoch 98/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7405
Epoch 99/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7418
Epoch 100/100
858/858 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7414

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 1s - loss: 0.5636 - accuracy: 0.7293 - 696ms/epoch - 3ms/step
Loss: 0.5635663866996765, Accuracy: 0.729300320148468

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(